
name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          wheel
          pylint
          mypy
          pytest
          pytest-cov
    - name: Typecheck
      run: mypy yadasm --disallow-untyped-defs
    - name: Check lint
      run: pylint yadasm
    - name: Run tests
      run: pytest yadasm/test/ -v
    - name: Code Coverage
      run: pytest --cov=.
