
name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Set up HLint'
      uses: haskell/actions/hlint-setup@v1
      with:
      version: '3.1.6'
    - name: Run lint
      run: hlint ./
    - name: Run tests
      run: cabal test
